# fly.toml app configuration file generated for folotoy-server on 2023-12-12T18:35:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "folotoy-server"
primary_region = "nrt"

[build]

[env]
  API_SERVER = "true"
  API_SERVER_BIND_ADDRESS = "0.0.0.0"
  API_SERVER_PORT = "80"
  AUDIO_DOWNLOAD_URL = "http://folotoy-server.fly.dev"
  AUDIO_SAVE_PATH = "/audio"
  LLM_TYPE = "openai"
  LOG_LEVEL = "DEBUG"
  MQTT_BROKER_HOST = "folotoy-mqtt.fly.dev"
  MQTT_BROKER_PORT = "1883"
  MQTT_CLIENT_ID = "folotoy"
  MQTT_PASSWORD = "folotoy"
  MQTT_USERNAME = "folotoy"
  OPENAI_OPENAI_KEY = "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"
  OPENAI_TTS_KEY = "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"
  OPENAI_TTS_MODEL = "tts-1"
  OPENAI_WHISPER_KEY = "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"
  OPENAI_WHISPER_MODEL = "whisper-1"
  ROLES_FILE_PATH = "/config/roles.json"
  SPEECH_UDP_SERVER_BIND_ADDRESS = "fly-global-services"
  SPEECH_UDP_SERVER_HOST = "folotoy-server.fly.dev"
  SPEECH_UDP_SERVER_PORT = "8085"
  STT_TYPE = "openai-whisper"
  TTS_TYPE = "edge-tts"
  TZ = "Asia/Shanghai"

[[services]]
  protocol = "udp"
  internal_port = 8085

  [[services.ports]]
    port = 8085

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    port = 80
