# fly.toml app configuration file generated for <your_app_name> on 2023-12-13T18:33:02+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "<your_app_name>"
#primary_region = "nrt"

[build]

[env]
  API_SERVER = "true"
  API_SERVER_BIND_ADDRESS = "0.0.0.0"
  API_SERVER_PORT = "8082"
  AUDIO_DOWNLOAD_URL = "http://<your_app_name>.fly.dev:8082"
  AUDIO_SAVE_PATH = "/audio"
  LLM_TYPE = "openai"
  LOG_LEVEL = "DEBUG"
  MQTT_BROKER_HOST = "127.0.0.1"
  MQTT_BROKER_PORT = "1883"
  MQTT_CLIENT_ID = "folotoy"
  MQTT_USERNAME = "folotoy"
  OPENAI_TTS_MODEL = "tts-1"
  OPENAI_WHISPER_MODEL = "whisper-1"
  ROLES_FILE_PATH = "/config/roles.json"
  SPEECH_UDP_SERVER_BIND_ADDRESS = "fly-global-services"
  SPEECH_UDP_SERVER_HOST = "<your_app_name>.fly.dev"
  SPEECH_UDP_SERVER_PORT = "8085"
  STT_TYPE = "openai-whisper"
  TTS_TYPE = "edge-tts"
  TZ = "Asia/Shanghai"

[[services]]
  protocol = "udp"
  internal_port = 8085

  [[services.ports]]
    port = 8085

[[services]]
  protocol = "tcp"
  internal_port = 8082

  [[services.ports]]
    port = 8082

[[services]]
  protocol = "tcp"
  internal_port = 1883

  [[services.ports]]
    port = 1883
