fly secrets set MQTT_PASSWORD="Ev6GoWrcDB"
fly secrets set OPENAI_OPENAI_KEY="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"
fly secrets set OPENAI_TTS_KEY="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"
fly secrets set OPENAI_WHISPER_KEY="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"
